name: API Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest  # Use Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn pytest requests pymongo

      - name: Start FastAPI server
        run: |
          Start-Process -NoNewWindow -FilePath "python" -ArgumentList "apiserver.py"
        shell: pwsh
      
      - name: Wait for server to be ready
        run: Start-Sleep -Seconds 10  # Ensure the server is running

      - name: Run tests
        run: pytest automation_test_pytest.py
