name: API Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest  # Use Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn pytest requests pymongo

      - name: Start MongoDB (Windows)
        run: |
          net start MongoDB
        continue-on-error: true  # Avoid breaking the pipeline if MongoDB is already running

      - name: Start FastAPI server
        run: |
          python apiserver.py &
      
      - name: Wait for server to be ready
        run: sleep 10  # Ensure the server is running

      - name: Run tests
        run: pytest testAutomation.py
