name: API Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest  # Use Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn pytest requests pymongo

      - name: Download and Extract MongoDB
        run: |
          Invoke-WebRequest -Uri "https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-6.0.6.zip" -OutFile mongodb.zip
          Expand-Archive -Path mongodb.zip -DestinationPath .

      - name: Start MongoDB Manually
        run: |
          mkdir -p C:\data\db
          Start-Process -NoNewWindow -FilePath "mongodb-windows-x86_64-6.0.6\bin\mongod.exe" -ArgumentList "--dbpath C:\data\db"
        shell: pwsh

      - name: Start FastAPI server
        run: |
          Start-Process -NoNewWindow -FilePath "python" -ArgumentList "apiserver.py"
        shell: pwsh
      
      - name: Wait for server to be ready
        run: Start-Sleep -Seconds 10  # Ensure the server is running

      - name: Run tests
        run: pytest automation_test_pytest.py
